# Generated by Django 4.0.3 on 2022-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationvo',
            name='import_href',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
