# Generated by Django 4.0.3 on 2022-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_remove_binvo_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
